// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-0SVG7MGuvjWXgV3Hm9kCbEa_e7yiONg',
    appId: '1:319361803378:web:e65124b24473d5c8324eeb',
    messagingSenderId: '319361803378',
    projectId: 'fix-chess',
    authDomain: 'fix-chess.firebaseapp.com',
    storageBucket: 'fix-chess.appspot.com',
    measurementId: 'G-71L2CGRM5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI-dkhNewNHQmSYkl2pYXdCltPKdqGZX8',
    appId: '1:319361803378:android:d087db39bc45c3af324eeb',
    messagingSenderId: '319361803378',
    projectId: 'fix-chess',
    storageBucket: 'fix-chess.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiH9eJO8OGmyAITETBiMfZKTI6cGhIYn4',
    appId: '1:319361803378:ios:4489e6839a12b02b324eeb',
    messagingSenderId: '319361803378',
    projectId: 'fix-chess',
    storageBucket: 'fix-chess.appspot.com',
    iosBundleId: 'com.example.onlineChess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiH9eJO8OGmyAITETBiMfZKTI6cGhIYn4',
    appId: '1:319361803378:ios:4489e6839a12b02b324eeb',
    messagingSenderId: '319361803378',
    projectId: 'fix-chess',
    storageBucket: 'fix-chess.appspot.com',
    iosBundleId: 'com.example.onlineChess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-0SVG7MGuvjWXgV3Hm9kCbEa_e7yiONg',
    appId: '1:319361803378:web:9c761dcf322b573c324eeb',
    messagingSenderId: '319361803378',
    projectId: 'fix-chess',
    authDomain: 'fix-chess.firebaseapp.com',
    storageBucket: 'fix-chess.appspot.com',
    measurementId: 'G-FJ8083PGHK',
  );
}
